export const mockExplanations: Record<string, Record<string, string | string[]>> = {
  "attempt-1-1": {
    mistakeSummary: "You likely confused integer and float types. The presence of a decimal point (3.14) makes it a float, not an integer.",
    rootCauseAnalysis: "You correctly identified that type() returns the data type of a value, but you overlooked that Python uses the decimal point as the key differentiator between int and float. Any number containing a decimal is automatically classified as a float, regardless of its mathematical equivalence to an integer.",
    correctConceptExplanation: "Python has several built-in numeric types:\n- **int**: Whole numbers (e.g., 3, -7, 42)\n- **float**: Numbers with decimal points (e.g., 3.14, -0.5, 2.0)\n- **complex**: Numbers with real and imaginary parts (e.g., 1+2j)\n\nThe `type()` function returns the type of any Python object. The decimal point is the key indicator — even `2.0` is a float.",
    simplifiedAnalogy: "Think of int and float like whole pizza boxes vs. pizza slices. An int is a complete, uncut box of pizza (whole number). A float is a slice of pizza with a fractional part. Even if you have exactly 2 full boxes, if you write it as 2.0 (with a decimal), Python treats it as a 'sliced' float. The decimal point is the knife that cuts the pizza.",
    stepByStepCorrection: "1. Look at the number 3.14\n2. Notice it has a decimal point (the '.' in 3.14)\n3. Python rule: ANY number with a decimal point is a float\n4. Therefore, type(3.14) returns <class 'float'>\n5. Memory trick: If you see a dot, it's a float — 'dot' = 'float'",
    preventionTips: "Remember the 'dot rule': if a number has a decimal point (a dot), it's a float. Practice by writing 5 different numbers and guessing whether they're int or float before checking with type().",
    relatedTopics: ["Python Data Types", "Type Conversion", "Numbers in Python"],
  },
  "attempt-1-2": {
    mistakeSummary: "You used 'function' instead of 'def' to define a function in Python, likely mixing up syntax from JavaScript or another language.",
    rootCauseAnalysis: "You understood that you need a keyword to define functions, which is correct thinking. However, you applied the keyword from another language (like JavaScript's `function`) instead of Python's `def`. This is a classic syntax transfer error that happens when learning multiple programming languages simultaneously.",
    correctConceptExplanation: "Python function definition syntax:\n```python\ndef function_name(parameters):\n    \"\"\"Docstring\"\"\"\n    # function body\n    return value\n```\n\nKey elements:\n- `def` keyword (required)\n- Function name (follows variable naming rules)\n- Parentheses for parameters\n- Colon `:` to start the function body\n- Indented body block",
    simplifiedAnalogy: "Think of `def` as a 'definition ceremony.' In Python, you're not just 'functioning' something (like in JavaScript) — you're 'defining' a new recipe. `def` is short for 'define,' like writing down a recipe in a cookbook. Every time you call the function, you're following that recipe.",
    stepByStepCorrection: "1. Start with the keyword `def`\n2. Give your function a name (e.g., `my_function`)\n3. Add parentheses `()` with any parameters inside\n4. End the line with a colon `:`\n5. Indent the function body\n6. Use `return` to send back a value\n\nExample:\n```python\ndef greet(name):\n    return f\"Hello, {name}!\"\n```",
    preventionTips: "Create a quick-reference card: Python = `def`, JavaScript = `function`, Java = `public static Type methodName()`. Review it before switching languages. Practice writing 3 different Python functions using `def` to build muscle memory.",
    relatedTopics: ["Python Functions", "Python vs JavaScript Syntax", "Function Parameters"],
  },
  "attempt-1-4": {
    mistakeSummary: "You identified tuple as mutable, but tuples are immutable — once created, their contents cannot be changed.",
    rootCauseAnalysis: "You correctly identified that both lists and tuples are sequence types that store ordered collections. However, you confused which one allows modification after creation. This often happens because tuples and lists look very similar visually, making their behavioral differences easy to overlook.",
    correctConceptExplanation: "**Mutable vs Immutable in Python:**\n\nMutable (can be changed):\n- `list` — `[1, 2, 3]`\n- `dict` — `{'a': 1}`\n- `set` — `{1, 2, 3}`\n\nImmutable (cannot be changed):\n- `tuple` — `(1, 2, 3)`\n- `str` — \"hello\"\n- `frozenset` — `frozenset({1, 2})`",
    simplifiedAnalogy: "Lists are like a whiteboard — you can write, erase, and rewrite information freely. Tuples are like an engraved stone tablet — once carved, the information is permanent. You can read it, but you can't change it without making a completely new engraving.",
    stepByStepCorrection: "1. Look at the brackets: `[ ]` = list (mutable), `( )` = tuple (immutable)\n2. Try to change a list: `my_list[0] = 99` ✅ works\n3. Try to change a tuple: `my_tuple[0] = 99` ❌ TypeError\n4. Memory trick: 'Tuple is Tough' (unchanging) — 'List is Limber' (flexible)",
    preventionTips: "Practice by creating a list and tuple with the same elements, then try modifying each. Note which one throws an error. The error message will reinforce the concept.",
    relatedTopics: ["Python Mutability", "Lists vs Tuples", "Immutable Types"],
  },
  "attempt-2-1": {
    mistakeSummary: "You answered 0, but the ternary expression `x if x > 3 else 0` returns 5 because x=5 and 5>3 is True.",
    rootCauseAnalysis: "You likely misread the conditional expression flow. In a ternary `x if condition else y`, the value before `if` is returned when the condition is True. Since 5 > 3 is True, the expression returns 5, not 0. You may have confused which value corresponds to True vs False.",
    correctConceptExplanation: "Python's ternary (conditional) expression:\n```python\nvalue_if_true if condition else value_if_false\n```\n\nFlow:\n1. Evaluate the condition\n2. If True → return value_if_true\n3. If False → return value_if_false",
    simplifiedAnalogy: "The ternary is like a fork in the road with a sign. The sign says: 'If True → go left (5). If False → go right (0).' Since the condition 'x > 3' evaluates to True, you go left and get 5. The 'else 0' is only for when you go right.",
    stepByStepCorrection: "1. Identify the condition: `x > 3`\n2. Substitute x = 5: `5 > 3` → True\n3. Since True, take the 'if-true' value: `x` = 5\n4. The 'else' value (0) is ignored\n5. Final result: 5",
    preventionTips: "Read ternary expressions aloud: 'X if condition else Y' → 'X is returned IF condition is true, ELSE Y is returned.' Practice reading 5 different ternary expressions out loud to train your brain.",
    relatedTopics: ["Conditional Expressions", "Ternary Operators", "Boolean Logic"],
  },
  "attempt-2-2": {
    mistakeSummary: "You said the loop executes 4 times, but range(5) generates 5 values (0, 1, 2, 3, 4).",
    rootCauseAnalysis: "You made a classic off-by-one error with range(). range(n) starts at 0 and goes UP TO n-1, so range(5) gives 5 values (0-4). You likely thought of range(5) as giving values 1-4 (4 values) or counted only the non-zero values.",
    correctConceptExplanation: "`range(stop)` generates integers from 0 to stop-1:\n- `range(5)` → 0, 1, 2, 3, 4 (5 values)\n- `range(3)` → 0, 1, 2 (3 values)\n\n`range(start, stop)` generates from start to stop-1:\n- `range(2, 5)` → 2, 3, 4\n\n`range(start, stop, step)`:\n- `range(0, 10, 2)` → 0, 2, 4, 6, 8",
    simplifiedAnalogy: "range(n) is like giving out tickets at a counter. The counter starts at 0 and shouts numbers until it reaches n, but it NEVER shouts n itself. So range(5) shouts: 0, 1, 2, 3, 4 — that's 5 shouts! The 5th person in line gets ticket 4.",
    stepByStepCorrection: "1. `for i in range(5):` means i takes each value from range(5)\n2. range(5) = [0, 1, 2, 3, 4] — that's 5 numbers\n3. print(i) runs for each of those 5 values\n4. Output: 0, 1, 2, 3, 4 (on separate lines)\n5. The loop body executes 5 times\n\nMemory trick: 'range(n) equals n items, starting at zero' 🎵",
    preventionTips: "Always test range() in a quick mental check: `list(range(5)) = [0,1,2,3,4]` has `len()` = 5. If you need n iterations, use range(n). If you need 1 through n, use range(1, n+1).",
    relatedTopics: ["range() Function", "Loop Iteration", "Off-by-One Errors"],
  },
  "attempt-2-3": {
    mistakeSummary: "You answered `break`, but `continue` is the keyword that skips to the next iteration of a loop.",
    rootCauseAnalysis: "You understood that there's a keyword for skipping loop iterations, which shows you know the concept exists. However, you confused `break` (which exits the entire loop) with `continue` (which skips only the current iteration). This is an extremely common confusion even among experienced programmers.",
    correctConceptExplanation: "Loop Control Keywords:\n\n`break` — Exits the loop immediately:\n```python\nfor i in range(10):\n    if i == 5:\n        break  # loop ends here\n    print(i)  # prints 0-4\n```\n\n`continue` — Skips to next iteration:\n```python\nfor i in range(5):\n    if i == 2:\n        continue  # skip this iteration\n    print(i)  # prints 0,1,3,4\n```",
    simplifiedAnalogy: "Imagine you're reading a book:\n- `break` = You close the book and stop reading entirely\n- `continue` = You skip the current boring paragraph and keep reading the next one\n\n`break` BREAKS out of the loop. `continue` CONTINUES with the next iteration.",
    stepByStepCorrection: "1. The question asks: 'skip to the next iteration'\n2. This is NOT exiting the loop (that's `break`)\n3. This is skipping ONE iteration and moving to the next\n4. The keyword for 'continue with next iteration' is... `continue`!\n5. Memory trick: 'continue' literally means 'continue with the next one'",
    preventionTips: "Use this memory trick: 'Break = Break out (exit). Continue = Continue on (skip one).' Write a small Python script that uses both `break` and `continue` and observe the different outputs.",
    relatedTopics: ["Loop Control", "break vs continue", "Loop Patterns"],
  },
  "attempt-2-5": {
    mistakeSummary: "You used `=` (assignment) instead of `==` (equality comparison) to check if x equals 10.",
    rootCauseAnalysis: "You correctly identified the need to check equality, which shows you understand the purpose. However, you confused the assignment operator `=` with the comparison operator `==`. This is the most common mistake in programming, especially for students coming from mathematics where `=` means equality.",
    correctConceptExplanation: "Assignment vs Comparison:\n\n`=` — Assignment operator:\n- `x = 10` assigns the value 10 to x\n- Used in variable assignments, function parameters\n\n`==` — Equality comparison:\n- `x == 10` checks if x equals 10 (returns True/False)\n- Used in if statements, while conditions",
    simplifiedAnalogy: "Think of `=` as 'setting a value' (SET) and `==` as 'asking a question' (CHECK).\n- `x = 10` = 'Set x to 10' (command)\n- `x == 10` = 'Is x equal to 10?' (question)\n\nYou can't ask a question with a command word. You need the question word: `==`.",
    stepByStepCorrection: "1. You need to CHECK if x equals 10\n2. Checking requires a QUESTION, not a command\n3. `=` is a command (assignment)\n4. `==` is a question (comparison)\n5. Correct: `x == 10`\n\nMemory trick: 'Assignment is singular (=), comparison is double (==) because you're comparing TWO things.'",
    preventionTips: "Every time you write `if (x =`, pause and check for double equals. Build a habit: write `==` as 'equals-equals' in your head. Practice by writing 5 assignment statements and 5 comparison statements.",
    relatedTopics: ["Comparison Operators", "Assignment vs Equality", "Python Operators"],
  },
  "attempt-3-3": {
    mistakeSummary: "You said Python functions can only return one value, but Python can return multiple values packed as a tuple.",
    rootCauseAnalysis: "You correctly understand that functions can return values to the caller. The misconception likely comes from other programming languages (like Java or C) where functions can indeed only return a single value. Python's ability to return multiple values as a tuple is a unique and powerful feature.",
    correctConceptExplanation: "Multiple Return Values in Python:\n\nPython functions can return multiple values packed as a tuple:\n```python\ndef min_max(numbers):\n    return min(numbers), max(numbers)\n\n# Unpacking\nlo, hi = min_max([3, 1, 4, 1, 5])\n# lo = 1, hi = 5\n```\n\nYou can return any number of values separated by commas. Python automatically packs them into a tuple.",
    simplifiedAnalogy: "Returning values in Python is like sending packages. Other languages are like a single-package courier — you can only send one box at a time. Python is like a multi-package courier — you can stack multiple boxes together (as a tuple) and send them all at once. The receiver can unpack them all in one go.",
    stepByStepCorrection: "1. Write `return` followed by values separated by commas\n2. Python automatically wraps them in a tuple: `return a, b` → `return (a, b)`\n3. The caller receives a tuple\n4. The caller can unpack: `x, y = function()`\n5. This is NOT returning multiple values literally — it's returning a SINGLE tuple containing multiple values\n\nExample:\n```python\ndef get_coordinates():\n    return 10, 20\n\nx, y = get_coordinates()  # x=10, y=20\n```",
    preventionTips: "Remember: 'Comma-separated after return = tuple packing.' Practice by writing a function that returns 3 different values and a caller that unpacks them.",
    relatedTopics: ["Tuples", "Return Values", "Unpacking"],
  },
  "attempt-3-5": {
    mistakeSummary: "You answered 3, but f(3) returns 5 because parameter b defaults to 2, making the result 3 + 2 = 5.",
    rootCauseAnalysis: "You recognized that f(3) calls the function with one argument, which is correct. However, you forgot that b has a default value of 2. When only one argument is passed, b automatically uses its default. You may have thought the function would error or that b would be 0.",
    correctConceptExplanation: "Default Parameters:\n```python\ndef f(a, b=2):\n    return a + b\n\nf(3)     # a=3, b=2 (default) → 5\nf(3, 10) # a=3, b=10 (override) → 13\n```\n\nRules:\n- Default parameters must come after non-default ones\n- The default is used only when the argument is omitted\n- You can override defaults by passing a value explicitly",
    simplifiedAnalogy: "Think of default parameters as a restaurant menu with 'default' options. When you order a burger (f(3)), you get it with the default toppings (b=2). If you want different toppings, you specify them (f(3, 10)). The default is always ready and waiting — you don't need to ask for it each time.",
    stepByStepCorrection: "1. The function signature is `f(a, b=2)` — b has a default of 2\n2. You call `f(3)` — only one argument provided\n3. Python assigns: a = 3 (first positional arg)\n4. Since b wasn't provided, it uses the default: b = 2\n5. The function computes: a + b = 3 + 2 = 5\n6. Final result: 5\n\nTo get 3, you'd need: `f(3, 0)` or change the default to `b=0`.",
    preventionTips: "When you see a function with default parameters, mentally insert the defaults for any missing arguments. Practice by tracing through 3 different function calls with different numbers of arguments.",
    relatedTopics: ["Default Parameters", "Function Arguments", "Keyword Arguments"],
  },
  "attempt-4-1": {
    mistakeSummary: "You said the last index is 5, but for a list of length 5, the last index is 4 because Python uses zero-based indexing.",
    rootCauseAnalysis: "You correctly understand that lists have a 'last element' and that it relates to length. However, you're counting starting from 1 instead of 0. With zero-based indexing, the first element is at index 0, so the 5th element is at index 4 (length - 1).",
    correctConceptExplanation: "Python Zero-Indexing:\n\nFor a list `arr = [10, 20, 30, 40, 50]` (length 5):\n- Index 0 → 10 (first)\n- Index 1 → 20\n- Index 2 → 30\n- Index 3 → 40\n- Index 4 → 50 (last)\n\nLength is always `len(arr)`, last index is always `len(arr) - 1`.",
    simplifiedAnalogy: "Zero-based indexing is like apartment numbers on a street. The first building is at position 0, the second at position 1, and so on. The 5th building is at position 4. Python doesn't ask 'which number apartment?' — it asks 'how many steps from the starting point?' The first element is 0 steps away.",
    stepByStepCorrection: "1. List length = 5 (elements at positions 1, 2, 3, 4, 5 in human counting)\n2. Python starts counting at 0, not 1\n3. Element 1 → index 0\n   Element 2 → index 1\n   Element 3 → index 2\n   Element 4 → index 3\n   Element 5 → index 4\n4. Last index = length - 1 = 5 - 1 = 4\n5. Memory trick: 'N elements = indices 0 to N-1'",
    preventionTips: "Whenever you need the last index, write `len(list) - 1` instead of just `len(list)`. Practice by creating a list with 10 elements and accessing each one by index to build muscle memory for 0-based thinking.",
    relatedTopics: ["List Indexing", "Zero-Based Indexing", "Negative Indices"],
  },
  "attempt-4-2": {
    mistakeSummary: "You said append returns the updated list, but it modifies the list in place and returns None.",
    rootCauseAnalysis: "You correctly understand that append() adds an element to the list — that's the right mental model. However, you assumed it returns the modified list like you might expect from JavaScript methods or from mathematical functions. In Python, methods that mutate objects in place conventionally return None.",
    correctConceptExplanation: "In-Place vs Returning Methods:\n\nMethods that modify in place return `None`:\n- `list.append(x)` → returns `None`\n- `list.sort()` → returns `None`\n- `list.reverse()` → returns `None`\n\nMethods that return new values:\n- `sorted(list)` → returns new sorted list\n- `list + [x]` → returns new list\n- `list.copy()` → returns new list",
    simplifiedAnalogy: "`append()` is like putting a book on a shelf. You're modifying the shelf (the list) by adding a book. The shelf doesn't give you anything back — it just changes. If you want to see the updated shelf, look at it directly (my_list), not at what append returned (which is just None, like an empty acknowledgment).",
    stepByStepCorrection: "1. `my_list.append(10)` adds 10 to the end of my_list\n2. The list is CHANGED in place (mutated)\n3. The return value of append() is `None`\n4. To see the updated list, check `my_list` not the return value\n5. If you write `result = my_list.append(10)`, result will be None\n6. Memory trick: 'mutators return None — only pure functions return values'",
    preventionTips: "Adopt the habit: if you're modifying an object, expect `None` back. If you want a new value, look for functions (like `sorted()`) not methods (like `sort()`). Practice by comparing `sorted(my_list)` vs `my_list.sort()`.",
    relatedTopics: ["List Methods", "In-Place Operations", "Method Return Values"],
  },
  "attempt-4-3": {
    mistakeSummary: "You said arr[3] accesses the third element, but because Python is zero-indexed, arr[2] is the third element.",
    rootCauseAnalysis: "This is another zero-indexing error, showing a pattern. You're thinking in 'human position' terms (1st, 2nd, 3rd) instead of 'computer offset' terms (0 steps, 1 step, 2 steps). The third element is 2 steps away from the start.",
    correctConceptExplanation: "Accessing List Elements:\n```python\narr = ['a', 'b', 'c', 'd', 'e']\narr[0]  # 'a' (1st element)\narr[1]  # 'b' (2nd element)\narr[2]  # 'c' (3rd element)\narr[3]  # 'd' (4th element)\narr[4]  # 'e' (5th element)\n```",
    simplifiedAnalogy: "Think of index as 'how many steps forward from the start.' To reach the first element, take 0 steps (you're already there). To reach the third element, take 2 steps forward: step 0 → step 1 → step 2. You're counting the GAPS between elements, not the elements themselves.",
    stepByStepCorrection: "1. To get the Nth element in Python, use index N-1\n2. 3rd element → index 3-1 = 2\n3. arr[2] correctly accesses the 3rd element\n4. arr[3] accesses the 4th element\n5. Memory trick: 'Position minus one equals index'",
    preventionTips: "Practice translating: 'Get the 5th element' → arr[4], 'Get the 1st element' → arr[0]. Do 10 of these translations mentally before your next quiz. This pattern takes deliberate practice to override the natural 1-based counting instinct.",
    relatedTopics: ["List Indexing", "Zero-Based Indexing", "Element Access"],
  },
  "attempt-4-5": {
    mistakeSummary: "You said the result is 5 (arithmetic addition), but the + operator on lists performs concatenation, resulting in [1, 2, 3, 4, 5].",
    rootCauseAnalysis: "You recognized that + is an operator acting on the lists, but you applied mathematical addition logic instead of list concatenation logic. This is an operator overloading misunderstanding — the same symbol (+) does different things for different data types. For numbers, + adds; for lists, + concatenates.",
    correctConceptExplanation: "List Concatenation:\n\nThe `+` operator on lists concatenates them:\n```python\n[1, 2, 3] + [4, 5]  # [1, 2, 3, 4, 5]\n['a'] + ['b']       # ['a', 'b']\n```\n\nPython uses operator overloading — the same operator behaves differently for different types.",
    simplifiedAnalogy: "The `+` operator is like a universal joint that connects things. For numbers, it 'connects' them arithmetically (3 + 2 = 5). For lists, it 'connects' them by joining them end-to-end like train cars. `[1, 2, 3]` connected to `[4, 5]` makes one long train: `[1, 2, 3, 4, 5]`.",
    stepByStepCorrection: "1. Identify the types: [1,2,3] is a list, [4,5] is a list\n2. The + operator between two lists means CONCATENATION, not addition\n3. Concatenation joins the second list to the end of the first\n4. Result: [1, 2, 3] + [4, 5] = [1, 2, 3, 4, 5]\n5. If you wanted arithmetic addition, you'd need a different approach: sum([1,2,3,4,5]) = 15\n\nMemory trick: 'List + List = Longer List (not a number)'",
    preventionTips: "Before using +, identify the data types: type + type = what? Number + Number = sum. List + List = combined list. String + String = concatenated string. Practice by writing 3 different type combinations with + and predicting the result.",
    relatedTopics: ["List Operations", "Operator Overloading", "List Concatenation"],
  },
}
